### ISSUE TITLE
Prometheus outside docker swarm

### ISSUE THREAD

**Issue by brunomanzo** [joonas-fi/promswarmconnect#9]
Hello there,

I have two clusters at the moment, one "old" of docker swarm and one "new" of kubernetes.
Currently prometheus runs on k8s, but I have a lot of services there still running on swarm cluster.
This can solve my SD problem? Know where the tasks are running outside swarm network.

**Comment by joonas-fi** [comment]
If I understood you correctly, then yes: promswarmconnect exposes enough details to discover services in your Swarm cluster (service names, IPs). The details it exposes are here: https://github.com/function61/promswarmconnect#verify-that-its-working

As for consumption of that API, pretty much nobody else than Prometheus uses this data format, so to actually use it somewhere else you'd have to write some code to bridge the gap to where you would want to use that data.

**Comment by brunomanzo** [comment]
Thank you =)
